### ISSUE TITLE
The 'ext' option doesn't have any effect

### ISSUE THREAD

**Issue by mjsarfatti** [smbeiragh/grunt-mjml#2]
As per the title. The result is that if I run the task in a certain folder and save the files in the same... all my mjml files will be overwritten with the compiled HTML!

**Comment by mjsarfatti** [comment]
**UPDATE**
It only happens if no "expanded" option is set.

**Comment by smbeiragh** [comment]
Yes! in fact it's grunt's files option feature:

> expand Set to true will enable the following properties:
>
> **cwd** All src matches are relative to (but don't include) this path.
> **src** Pattern(s) to match, relative to the cwd.
> **dest** Destination path prefix.
> **ext** Replace any existing extension with this value in generated dest paths.
> **extDot** Used to indicate where the period indicating the extension is located. Can take either 'first' (extension begins after the first period in the file name) or 'last' (extension begins after the last period), and is set by default to 'first' [Added in 0.4.3]
> **flatten** Remove all path parts from generated dest paths.
> **rename** Embeds a customized function, which returns a string containing the new destination and filename. This function is called for each matched src file (after extension renaming and flattening).

http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically
