### ISSUE TITLE
Ignore error messages

### ISSUE THREAD

**Issue by adamjw3** [smbeiragh/grunt-mjml#3]
On <mj-social> you can have your own custom attributes for social links that arent included, in my case youtube. So following the mjml documentation i've added these but i get fatal error when running my task 

my task is as follows:

`
mjml: {
            // MJML task (any templates or component files that have mjml code
            frontend: {
                files: {
                    'dist/email.html': 'dist/email.html',
                    'dist/component-all.html': 'dist/component-all.html',
                    'dist/component-cta.html': 'dist/component-cta.html',
                    'dist/component-content.html': 'dist/component-content.html',
                    'dist/component-header.html': 'dist/component-header.html',
                    'dist/component-masthead.html': 'dist/component-masthead.html',
                    'dist/component-navbar.html': 'dist/component-navbar.html',
                    'dist/component-button.html': 'dist/component-button.html',
                    'dist/component-footer.html': 'dist/component-footer.html',
                    'dist/component-spacer.html': 'dist/component-spacer.html',
                }
            }
        },
`

and the wrror i get is in the footer.html where the mj-socail is 

`
>> error processing file dist/component-footer.html
Fatal error: [
    {
        "line": 34,
        "message": "Attributes youtube-href, youtube-icon-color, youtube-icon are illegal",
        "tagName": "mj-social",
        "formattedMessage": "Line 34 (mj-social) — Attributes youtube-href, youtube-icon-color, youtube-icon are illegal"
    }
]
`

Anyway to Ignore these errors?

**Comment by smbeiragh** [comment]
Look likes a mjml thing. Check the mjml documentations or test it using mjml cli.
This issue is so far old, I will close it.
