### ISSUE TITLE
Validation Level

### ISSUE THREAD

**Issue by corentincaton** [smbeiragh/grunt-mjml#6]
Is there a way to set the [validation level](https://mjml.io/documentation/#validating-mjml) with grunt-mjml ? 

I tried the following without success:
```
mjml: {
        options: {
            validationLevel: 'skip'
        }
```

Thanks !

**Comment by smbeiragh** [comment]
Try using .mjmlconfig file
[https://mjml.io/documentation/#in-javascript](https://mjml.io/documentation/#in-javascript)

currently, I don't pass grunt options to mjml. I will fix it soon.

**Comment by corentincaton** [comment]
Hi, 
Thanks for your answer, I'll try that.
